services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: online_shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Add volume for data persistence

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/online_shop_db
      SECRET_KEY: change-me-in-prod
    ports:
      - "8000:8000" # Fixed port mapping
# Optional: for development with hot reload

volumes:
  postgres_data:
